// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/jobrunner/JobCard.tsx": () => import("../components/mockups/jobrunner/JobCard.tsx"),
  "./components/mockups/jobrunner/TemplatesHub.tsx": () => import("../components/mockups/jobrunner/TemplatesHub.tsx")
};
