// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/signup-screen/OptionA.tsx": () => import("../components/mockups/signup-screen/OptionA.tsx"),
  "./components/mockups/signup-screen/OptionB.tsx": () => import("../components/mockups/signup-screen/OptionB.tsx"),
  "./components/mockups/signup-screen/OptionC.tsx": () => import("../components/mockups/signup-screen/OptionC.tsx")
};
