import re
src = open('shared/schema.ts').read()
var2tbl = {}
for m in re.finditer(r'export const (\w+) = pgTable\(\s*"([^"]+)"', src):
    var2tbl[m.group(1)] = m.group(2)
lines = src.split('\n'); cur=None; rels=[]
for ln in lines:
    mt=re.search(r'export const (\w+) = pgTable\(\s*"([^"]+)"', ln)
    if mt: cur=mt.group(2)
    mc=re.search(r'\w+\("([^"]+)"[^)]*\)[^,]*\.references\(\(\)\s*=>\s*(\w+)\.(\w+)', ln)
    if mc and cur:
        col=mc.group(1); parent=var2tbl.get(mc.group(2),mc.group(2)); pcol=mc.group(3)
        not_null = '.notNull()' in ln
        od = re.search(r"onDelete:\s*'(\w[\w ]*)'", ln)
        on_delete = od.group(1) if od else None
        rels.append((cur,col,parent,pcol,not_null,on_delete))
# dedupe preserving order
seen=set(); uniq=[]
for r in rels:
    k=(r[0],r[1],r[2],r[3])
    if k in seen: continue
    seen.add(k); uniq.append(r)
rels=uniq

stmts=[]
n_del=n_upd=0
for child,col,parent,pcol,not_null,on_delete in rels:
    if child==parent: continue
    orphan_pred=(f'c."{col}" IS NOT NULL AND NOT EXISTS '
                 f'(SELECT 1 FROM "{parent}" p WHERE p."{pcol}" = c."{col}")')
    # Choose remediation:
    #  set null  -> null the column (preserve the row)
    #  cascade   -> delete the orphan row (faithful to cascade)
    #  otherwise -> not-null column has no choice but delete; nullable -> null
    if on_delete == 'set null':
        action='update'
    elif on_delete == 'cascade':
        action='delete'
    else:
        action='delete' if not_null else 'update'
    if action=='update':
        n_upd+=1
        stmts.append(
          f'    UPDATE "{child}" c SET "{col}" = NULL WHERE {orphan_pred};\n'
          f'    GET DIAGNOSTICS rc = ROW_COUNT; total := total + rc;\n'
          f"    IF rc > 0 THEN RAISE NOTICE 'nulled % orphaned \"{child}\".\"{col}\"', rc; END IF;")
    else:
        n_del+=1
        stmts.append(
          f'    DELETE FROM "{child}" c WHERE {orphan_pred};\n'
          f'    GET DIAGNOSTICS rc = ROW_COUNT; total := total + rc;\n'
          f"    IF rc > 0 THEN RAISE NOTICE 'deleted % orphaned \"{child}\" rows (missing \"{parent}\")', rc; END IF;")
body="\n".join(stmts)
sql=f"""-- Auto-generated by scripts/gen-cleanup.py. DO NOT EDIT BY HAND.
-- Resolves orphaned rows (children referencing deleted parents) so the foreign
-- keys declared in shared/schema.ts can be created by `drizzle-kit push`.
--
-- Remediation matches the declared FK behavior:
--   * onDelete 'set null'  -> set the column to NULL (preserve the record)
--   * onDelete 'cascade'   -> delete the orphan row (the parent is gone)
--   * otherwise            -> NOT NULL column: delete; nullable column: set NULL
--
-- Safe + idempotent: a no-op once the cascade FKs exist. It loops to a fixpoint
-- because resolving one orphan can expose orphans in tables that referenced it,
-- and aborts if a single pass would touch an implausibly large number of rows
-- (guards against an accidental mass-mutation from a future schema bug).
DO $$
DECLARE rc int; total int; passes int := 0; MAX_PER_PASS constant int := 100000;
BEGIN
  LOOP
    total := 0; passes := passes + 1;
{body}
    IF total > MAX_PER_PASS THEN
      RAISE EXCEPTION 'orphan cleanup touched % rows in one pass (> %); aborting as a safety guard', total, MAX_PER_PASS;
    END IF;
    EXIT WHEN total = 0 OR passes >= 12;
  END LOOP;
  RAISE NOTICE 'orphan cleanup finished in % pass(es)', passes;
END $$;
"""
open('scripts/cleanup-orphans.sql','w').write(sql)
print(f"wrote scripts/cleanup-orphans.sql: {n_del} delete blocks, {n_upd} set-null blocks")
